site_name: Streetscapes
repo_url: https://github.com/Urban-M4/streetscapes
nav:
  - Overview: index.md
  - Tutorials:
      - Introduction: tutorial/tutorial.md
      - Streetscapes CLI: tutorial/cli.md
      - Local images: tutorial/local-images.md
      - Access database from Python: tutorial/manual-database-access.ipynb
  - Examples:
      - Exploring Global Streetscapes: examples/explore_global_streetscapes.ipynb
      - Converting CSV files into Parquet: examples/convert_csv_to_parquet.ipynb
      - Using data sources: examples/use_data_sources.ipynb
      - Segmenting downloaded images: examples/segmentation.ipynb
      - Rasterise data: examples/rasterise.ipynb
  - About:
      - Licence: about/licence.md
      - Contributing: about/contributing.md
      - Citation: about/citation.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue grey
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: cyan

  features:
    - navigation.footer
  font:
    text: Roboto
    code: Roboto Mono
  locale: en
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: src
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            group_by_category: false
            relative_crossrefs: true
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: true
      include_source: true
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
hooks:
  - docs/mermaid-hook.py
