[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "streetscapes"
version = "0.3.2"
requires-python = ">= 3.12"
dependencies = [
    "black",
    "contextily",
    "cyclopts>=4.2.1",
    "duckdb",
    "environs",
    "ephem",
    "filetype",
    "fiona",
    "geodatasets",
    "geopandas",
    "h3",
    "h5netcdf",
    "huggingface_hub[cli]",
    "humanize",
    "ibis-framework[duckdb,geospatial]",
    "imageio[pyav]",
    "ipykernel",
    "ipywidgets",
    "loguru",
    "matplotlib",
    "mit-semseg",
    "numpy",
    "orjson",
    "osmnx",
    "pandas",
    "pillow>=11.3.0",
    "pyarrow",
    "pygeohash>=3.2.0",
    "pyproj",
    "rasterio",
    "ray[serve]>=2.51.1",
    "rich",
    "safetensors>=0.6.2",
    "sam2",
    "scikit-image",
    "scipy",
    "seedir",
    "tabulate>=0.9.0",
    "timezonefinder",
    "torch",
    "torchvision",
    "tqdm",
    "transformers",
    "uuid7gen",
    "typer>=0.23.0",
]
authors = [
    { name = "Claire Donnelly", email = "c.donnelly@esciencecenter.nl" },
    { name = "Alexander Hadjiivanov", email = "a.hadjiivanov@esciencecenter.nl" },
    { name = "Peter Kalverla", email = "p.kalverla@esciencecenter.nl" },
    { name = "Bart Schilperoort", email = "b.schilperoort@esciencecenter.nl" }
]
description = "Code for downloading, segmenting and analysing images from Mapillary and KartaView, with the aim of extracting the emissivity and albedo of buildings."
readme = "README.md"
license = { file = "LICENCE.md" }

[project.scripts]
streetscapes = "streetscapes.cli.main:app"
streetscapes-explorer = "streetscapes.explorer.server:serve"

[tool.ruff]
lint.select = ["F", "E", "TYP", "B", "D", "C", "Q", "I"]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[project.optional-dependencies]
explorer = [
    "fastapi",
    "uvicorn",
]
dev = [
    "fastapi[standard]",
    "pytest>=8.4.2",
    "mimesis",
    "ruff",
    "py-spy",
    "mike",
    "mkdocs",
    "mkdocstrings[python]",
    "mkdocs-autoapi>=0.4.1",
    "mkdocs-material",
    "mkdocs-jupyter",
]
