name: Python Tests

on:
  pull_request

jobs:

  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
    
      - name: Setup uv with cache and python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Test with python ${{ matrix.python-version }}
        run: uv run pytest -v
        # TODO: add --frozen but requires lockfile in env
