name: Lint with Ruff

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Install Ruff
        run: pip install ruff

      - name: Run format check
        id: ruff-format
        run: |
          ruff format src --check

      - name: Run Ruff linter
        id: ruff-linter
        run: |
          ruff check src --output-format github